apiVersion: apps/v1
kind: Deployment
metadata:
  name:  gitlab-image
  namespace: default
  labels:
    app:  gitlab
spec:
  selector:
    matchLabels:
      app: gitlab-image
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  gitlab-image
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  gitlab-image
        image:  registry.gitlab.envent.ru:5005/root/docker-frontend-2:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: MY_HOST
          valueFrom:
            configMapKeyRef:
              name: gitlab-image
              key: MY_HOST
        ports:
        - containerPort:  80
          name:  gitlab-image
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Europe/Moscow
      restartPolicy: Always
      imagePullSecrets:
      - name: gitlab-registry