apiVersion: v1
kind: Pod
metadata:
  name: docker-frontend-2
spec:
  containers:
  - name: docker-frontend-2-app
    image: registry.gitlab.envent.ru/root/docker-frontend-2:1.0
    livenessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 90
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 90
      periodSeconds: 10
  imagePullSecrets:
  - name: gitlab-registry